# Generated by Django 6.0 on 2026-05-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cantidade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('tempada', models.CharField(max_length=50)),
                ('preparacion', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='recetas/')),
                ('ingredientes', models.ManyToManyField(to='recetas.ingrediente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('platos', models.ManyToManyField(to='recetas.plato')),
            ],
        ),
    ]
